services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5434:5432
    volumes:
      - /usr/share/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.yml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=admin
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend: